module recoLocalTrackerSiPixelClusterizePluginsGPUClusteringConstants

include("../CUDADataFormats/gpu_clustering_constants.jl")
using .CUDADataFormatsSiPixelClusterInterfaceGPUClusteringConstants

end # module recoLocalTrackerSiPixelClusterizePluginsGPUClusteringConstants