module recoLocalTrackerSiPixelClusterizePluginsGPUClusteringConstants

include("../CUDADataFormats/gpu_clustering_constants.jl")
using .CUDADataFormatsSiPixelClusterInterfaceGPUClusteringConstants: gpuClustering

end # module recoLocalTrackerSiPixelClusterizePluginsGPUClusteringConstants